name: Sync Other Repository

on:
  push:
    branches:
      - master
  workflow_dispatch:    
jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout other repository
        uses: actions/checkout@v3
        with:
          repository: Ygria/health
          path: public
          token: ${{ secrets.HEALTH_TOKEN}} # 使用自定义的 token   
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Apple Health Sync  # 提交者的GitHub用户名
          author_email: Apple Health Sync  # 提交者的电子邮件
          message: 'Automatically commit changes'  # 提交信息
          add: '.'  # 添加当前目录下的所有变更
          
